### PR TITLE
Add dialog to download dictionaries

### PR DESCRIPTION
**Pull request by zjosua**
Simple UI to download dicts from the chromium repo.

You may of course rewrite this to not require the use of the Qt Designer.

### CODE REVIEW

**Comment by BlueGreenMagick** [comment]
This is amazing!

I found one minor problem - If you actually try to download without internet connection, error occurs because 'showInfo' is not imported. Otherwise everything looks good to me!

I think it's fine to add new dialogs in qt designer format if you are more comfortable with that. I'd just rather not go out of my way to convert existing dialogs to qt designer format.

**Comment by BlueGreenMagick** [comment]
Also, if you know how to use python(mypy) type hints, it would be great if new code had type hints. We will probably want to type check the addon in the future.

If you don't know that's fine too! Half the code doesn't have type hints anyway

**Comment by AnKingMed** [comment]
Looks super cool! Can you update the README with instructions for use if there is anything pertinent? @BlueGreenMagick go ahead and merge this once the one small error is resolved

@AnKing-Forrest is planning to release this add-on, but I messaged Lovac first to see if perhaps it would make more sense to take over his AnkiWeb listing and just release it there

**Comment by zjosua** [comment]
I haven't really used type hints myself, but I was thinking about learning it a few times.
Might as well start here. But it well probably take a few iterations to get it right, so I suggest doing it in another PR.

**Comment by AnKingMed** [comment]
Sounds reasonable. We just need to fix this then, right?

> I found one minor problem - If you actually try to download without internet connection, error occurs because 'showInfo' is not imported. Otherwise everything looks good to me!

**Comment by zjosua** [comment]
Yes that's in the commit I pushed a few minutes before your first comment.

**Comment by AnKingMed** [comment]
Oh I missed that sorry!

**Comment by AnKingMed** [comment]
After merging I just built this and tested and now I'm getting this error (2.1.54 Qt5)

> When loading '⁨Spell Checker with Custom Dictionaries⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 244, in loadAddons
  File "/Users/Nick/Library/Application Support/Anki2/addons21/1410276506/__init__.py", line 12, in <module>
    from . import spellpopo
  File "/Users/Nick/Library/Application Support/Anki2/addons21/1410276506/spellpopo.py", line 20, in <module>
    from .dict import DictionaryManager
  File "/Users/Nick/Library/Application Support/Anki2/addons21/1410276506/dict.py", line 17, in <module>
    from .gui.get_dicts import invokeGetDicts
  File "/Users/Nick/Library/Application Support/Anki2/addons21/1410276506/gui/get_dicts.py", line 16, in <module>
    from .forms import get_dicts
ImportError: cannot import name 'get_dicts' from '1410276506.gui.forms' (unknown location)

**Comment by zjosua** [comment]
Did you build with aab?

**Comment by BlueGreenMagick** [comment]
@AnKingMed You need to run `aab ui` whenever a .ui file is modified.

If you don't have aab installed, run `python -m pip install git+https://github.com/glutanimate/anki-addon-builder.git`

I'll add that to the README

**Comment by AnKingMed** [comment]
Gotcha. @BlueGreenMagick can you just convert this to the format we use with our other addons that has the GitHub action?

**Comment by BlueGreenMagick** [comment]
Our github action actually supports this setup, but it looks like [recent aab release broke it](https://github.com/glutanimate/anki-addon-builder/issues/23).

I copied the generated python code into addon code. The new release should work fine.

**Comment by AnKingMed** [comment]
Cool, thanks. Is Glutanimate planning on fixing that? Happy to have one of you guys do it if he needs help
